{{- $fullName := include "local.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "local.name" . }}
    helm.sh/chart: {{ include "local.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
# {{- if .Values.ingress.tls }}
#   tls:
#   {{- range .Values.ingress.tls }}
#     - hosts:
#       {{- range .hosts }}
#         - {{ . | quote }}
#       {{- end }}
#       secretName: {{ .secretName }}
#   {{- end }}
# {{- end }}
  rules:
  - host: "{{ .Release.Namespace }}.{{ .Values.domainName }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: http
